### ISSUE TITLE
Multiple definition of gMissionCompletionState 

### ISSUE THREAD

**Issue by andre-vm** [SoapyMan/REDRIVER2#33]
Hello!

First of all, let me tell you: this project is awesome! Having the opportunity to play Driver 2 as it is, but in a decent and stable frame rate, with support for widescreen and with faster loading times is so cool! So thank you for the initiative!

I've been trying to compile this on Linux, and I've had some success solving most of the issues. But I'm not sure how to solve this one:

```
/usr/bin/ld: obj/Debug/REDRIVER2/PAUSE.o:GAME/C/PAUSE.C:45: multiple definition of `gMissionCompletionState';
obj/Debug/REDRIVER2/GLAUNCH.o:GAME/C/GLAUNCH.C:705: first defined here
```

```
// PAUSE.C
PAUSEMODE gMissionCompletionState = PAUSEMODE_GAMEOVER; // Has value 3
```

```
// GLAUNCH.C
int gMissionCompletionState = 0;
```

**Comment by andre-vm** [comment]
Nevermind.. `linkoptions { "-z muldefs" }` on premake5.lua did the trick.

**Comment by SoapyMan** [comment]
Hey Andre! Thanks!

I fixed it anyway in my dev branch! 
Thanks for the submission!
